#!/usr/bin/env bash

if [[ $1 =~ ^[0-9]+$ ]]
then
	if [[ ($1 == 1) || ($1 == 0) ]]
	then 
		echo 1
	else
		n=$(( $1-1 ))
		n=$(bash $0 $n)
		echo $((n * $1))
	fi
else
	echo parametre invalide!
	exit 1
fi




